Vizzuality/4-growth

- README.md
- api/README.md
- api/package.json
- client/package.json
- client/pnpm-workspace.yaml
- client/tsconfig.json
- package.json
- pnpm-lock.yaml
- pnpm-workspaces.yaml
- tsconfig.json
This PR architectures the project as a mono-repo, leveraging pnpm workspaces.
It adds a base tsconfig in the root, with paths to both api and client, and a common package.json to run the apps
> (chore) Create mono-repo

- api/src/typeorm.config.ts
- shared/dto/custom-charts/custom-chart-filter.entity.ts
- shared/dto/custom-charts/custom-chart.entity.ts
- shared/dto/users/user.entity.ts
- shared/lib/db-entities.ts
- shared/lib/e2e-test-manager.ts
This PR adds 2 new DB entities: Custom Charts and Chart Filters
The entities are defined in `shared/dto/custom-charts`
These are loaded into typeorm.config so that when the api is launched, the model is recreated in the DB.
Since this does not include any functionality and the purpose is to unblock other tasks, there are no tests, which will be added in next task when we actually retrieve stuff using this new tables
> (chore) Update data model: Add custom charts

- api/src/app.module.ts
- api/src/modules/api-events/api-events.module.ts
- api/src/modules/api-events/api-events.service.ts
- api/src/modules/auth/auth.service.ts
- api/src/modules/auth/password/password-recovery-email.service.ts
- api/src/modules/users/users.service.ts
- api/test/api-events/api-events.spec.ts
- pnpm-lock.yaml
- shared/dto/api-events/api-event.types.ts
- shared/dto/api-events/api-events.entity.ts
- shared/lib/db-entities.ts
Introduces a historic registry for significant api events, that are registered in a api_events table in the database.
since currently we don't have a big amount of events, the system is coupled to a single service, but we can extend it to use a event based system to decouple different types of events for specific providers. I have considered an event based approach would introduce a complexity that is not needed and its not clear if we will ever need to.
Aditionaly, we could create views based on different types of events for easier check and maintenance
> (chore) SIRH-94 create api events

- client/package.json
- client/src/containers/auth/forgot-password/email-form/index.tsx
- client/src/containers/header/menu/index.tsx
- client/tests/contact-us-form.test.tsx
- client/tests/forgot-password-email-form.test.tsx
- client/tests/new-password-form.test.tsx
- client/tests/use-api-response-toas-with-component.test.tsx
- client/tsconfig.json
- pnpm-lock.yaml
This PR adds a backlink in the menu component to the main 4-growth project web
**BUT MORE IMPORTANTLY:**
It attempts to fix the lack of typing in client component tests.
We could use several approaches, Ive decided to go with the one that I think its the best, but I am happy to discuss it before pushing this.
The decided approach:
1. Fixes lack of typing in global jest's `expect` by adding a global import in the setup before env file which is loaded by the jest config, and adding types in clients ts compiler options.
2. Fixes the lack of typing for mocked library/functions/whatever by wrapping them with jest-mock's `mocked` function.
Still, mocking the whole file by jest is required.
Since now the type inheritance is working, there is a need to cast mock responses to mocked libraries and …
> (feat) SIRH-97 backlinck from vis tool page

- client/package.json
- client/src/containers/coming-soon/index.tsx
- package.json
https://vizzuality.atlassian.net/browse/SIRH-96
> [SIRH-96] adds backlink to project site

- .github/workflows/deploy.yml
This PR aims to simplify the Deployment pipeline:
1-Removes "redundant" extract branch name steps to get the branch name which matches some deployment environment name
2-Adds an additional job to set the environment name by the branch name to inject the value in `$GITHUB_OUTPUT`
3-Then subsequent jobs are dependant of this job and can reference the value internally within the job.
It would be amazing if we could just set a global `env_name` at the top and then reference it everywhere which would make the thing much more clear, but not all sys variables are available at every step of the process, and then not all properties of the workflow allow using expressions to compute a value, I found this to be the most clean approach so far.
Additionally, it removes a couple of steps that were …
> (chore) simplify deployment pipeline

- api/test/users/custom-widgets/custom-widget-crud.spec.ts
- client/src/containers/profile/saved-visualizations/table/index.tsx
- shared/contracts/sections.contract.ts
- shared/contracts/users.contract.ts
- shared/schemas/query-param.schema.ts
- refactor(front): Add type assertion on the frontend for dynamically generated QueryParams (SortQueryParam<CustomWidget>)
- refactor: Remove old FetchSpecificationSchema from requests that fetch data and replace it in favour of generateEntityQuerySchema
- test(api): Activate disabled test for custom-widget
-  feat: Add generateEntityQuerySchema in order to generate queryParams validation for contracts
> Entity query validator

- api/data/sections-csv-parser.ts
- api/src/infrastructure/data-source-manager.ts
- api/src/modules/auth/auth.module.ts
- api/src/modules/email/email.module.ts
- api/src/modules/logging/logging.module.ts
- api/src/modules/sections/sections.module.ts
- api/src/modules/users/users.module.ts
- api/src/modules/widgets/widgets.module.ts
- api/test/app.spec.ts
- api/test/auth/auth.spec.ts
- api/test/data-source-manager.spec.ts
- api/test/utils/test-manager.ts
- test: Add tests for data-source-manager.ts and app initialization
- test: Update test Manager in order so it allows manual initialization when the instance is returned
- fix(api): When initial data is loaded, section order start at 1 instead of 2
> Test seed database

- api/src/infrastructure/sql-adapter.ts
- api/test/sections/sections-crud.spec.ts
- shared/schemas/widget-data-filters.schema.ts
- Bugfix
- Changed property name from "value" to "values" (makes more sense since each filter can have 1 or more values, and it translates to type string[] )
> Bugfix parsing filterQuerySchema

- client/src/app/(root)/layout.tsx
- client/src/containers/explore/index.tsx
- client/src/containers/filter/filter-select/filter-select-values/index.tsx
- client/src/containers/filter/filter-select/index.tsx
- client/src/containers/sidebar/filter-settings/filter-popup/index.tsx
- client/src/containers/sidebar/filter-settings/index.tsx
- client/src/containers/sidebar/index.tsx
- client/src/containers/sidebar/sections-nav/index.tsx
- client/src/containers/sidebar/store.ts
- client/src/hooks/useFilters.ts
- client/src/lib/queryKeys.ts
- client/tests/filter-select/filter-select-values.test.tsx
- client/tests/hooks/useFilters.test.ts
- Filters can now be added/removed which will auto-update the url + state 
- Validation for filter name has been removed, since this will be of type string in the near future
- Invalid filters will currently return an error message response from the API, but to keep the frontend state easily in sync with the backend the API response will (soon) return all sections and only filter the widget data
- The following filters can be used to test: eu-member-state (France,Spain), sector
[SIRH-126](https://vizzuality.atlassian.net/browse/SIRH-126)
[SIRH-126]: https://vizzuality.atlassian.net/browse/SIRH-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Apply filters to widgets

- api/src/modules/sections/sections.controller.ts
- api/src/modules/widgets/widgets.service.ts
- api/test/e2e/widgets/base-widgets.spec.ts
- client/src/app/(root)/layout.tsx
- client/src/containers/explore/index.tsx
- client/src/containers/sidebar/sections-nav/index.tsx
- shared/contracts/sections.contract.ts
- shared/schemas/widget-visualisation-filters.schema.ts
This pull request includes changes to the `WidgetsService` class, test cases for base widgets, and the widget visualization filter schema. The most important changes involve refactoring the `extendGetByIdQuery` method, adding a new test case, and making the `visualisations` array optional in the schema.
Refactoring and bug fixes:
* [`api/src/modules/widgets/widgets.service.ts`](diffhunk://#diff-a0170ae4a17f3df69749240e00c40c602ef93f54e8c63ad0eeba0381cc351786L30-R36): Refactored the `extendGetByIdQuery` method to handle cases where `fetchSpecification.visualisations` is undefined or empty, ensuring the query is always returned.
Testing improvements:
* [`api/test/e2e/widgets/base-widgets.spec.ts`](diffhunk://#diff-db7a15d5bd306a7fc40647f0523161f51c760a6ff4efe993286edf5e5252b10fR3-R45): …
> fixes visualisation filter required for widgets

- client/src/app/globals.css
- client/src/components/icons/no-data.tsx
- client/src/containers/explore/section/overview-section/index.tsx
- client/src/containers/no-data/index.tsx
- client/src/containers/widget/index.tsx
- client/tailwind.config.ts
- client/tests/no-data.test.tsx
[design](https://www.figma.com/design/1MQAbB99h05eR5xbHqNDVn/4Growth-%5BInternal%5D?node-id=6751-15648&t=IvYkK4WvZoUTfsK4-4)
- You could alter the util function `isEmptyWidget` to always return true
[SIRH-143](https://vizzuality.atlassian.net/browse/SIRH-143)
[SIRH-143]: https://vizzuality.atlassian.net/browse/SIRH-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated styles no-data component

- client/src/containers/explore/section/index.tsx
- client/src/containers/explore/section/overview-section/index.tsx
- client/src/containers/explore/section/tile-menu/index.tsx
- client/src/containers/sidebar/sections-nav/index.tsx
- client/src/lib/utils.ts
- e2e/tests/auth/auth.spec.ts
- e2e/tests/auth/password-recovery.spec.ts
- e2e/tests/custom-widgets/custom-widgets.spec.ts
- e2e/tests/explore/explore.spec.ts
- e2e/tests/users/users.spec.ts
- shared/lib/e2e-test-manager.ts
Updates E2E test approach to run against existing database state instead of clearing it. Test data is now created and cleaned up individually, better mimicking real-world scenarios.
Changes:
- Removed database clearing hooks
- Add targeted cleanup for test-specific data
- Maintain existing database state during tests
- Small refactor accessibility section navigation (frontend)
> Refactor E2E tests to support production-like database state

- .github/workflows/deploy.yml
This pull request includes a small change to the `jobs` section in the `.github/workflows/deploy.yml` file. The change removes the `timeout-minutes` parameter.
> chore(infrastructure): Remove deploy.yaml jop step timeout

- client/package.json
- client/src/components/ui/tooltip.tsx
- client/src/containers/sidebar/index.tsx
- client/src/containers/sidebar/indicator-seletor/index.tsx
- client/src/containers/sidebar/visualization-selector/index.tsx
- pnpm-lock.yaml
- Force user to select indicator first by disabling the visualization selector
- Disable visualization selection from list if combination is not possible
- Removed "single value" from visualization selection
[Figma flow](https://www.figma.com/proto/1MQAbB99h05eR5xbHqNDVn/4Growth-%5BInternal%5D?page-id=3103%3A1244&node-id=6842-15645&node-type=frame&viewport=-13771%2C1965%2C1&t=Nspde3dObHoE7E0h-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6842%3A15645&show-proto-sidebar=1)
[Figma design](https://www.figma.com/design/1MQAbB99h05eR5xbHqNDVn/4Growth-%5BInternal%5D?node-id=6842-15645&t=5p9hCakvz2VRuP7w-4)
> Conditionally disable visualization selector in sandbox

- client/src/components/icons/menu-pointer.tsx
- client/src/containers/no-data/index.tsx
- client/src/containers/sandbox/index.tsx
- client/tests/no-data.test.tsx
[FIgma](https://www.figma.com/design/1MQAbB99h05eR5xbHqNDVn/4Growth-%5BInternal%5D?node-id=6842-15645&m=dev)
[SIRH-178](https://vizzuality.atlassian.net/browse/SIRH-178)
[SIRH-178]: https://vizzuality.atlassian.net/browse/SIRH-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE - implement screen when there is nothing to show

- client/src/containers/header/index.tsx
- client/src/containers/header/menu/index.tsx
- Redirect to sandbox page when clicking on "4Growth Visualization Platform" logo
- Display links to /explore and /sandbox when not on 1 of these pages
[SIRH-194](https://vizzuality.atlassian.net/browse/SIRH-194)
[SIRH-194]: https://vizzuality.atlassian.net/browse/SIRH-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE - add a way to go back to the sandbox from the profile screen

- client/src/containers/explore/section/overview-section/index.tsx
- client/src/containers/explore/survey-analysis/index.tsx
- client/src/containers/sandbox/user-sandbox/index.tsx
- client/src/containers/sidebar/indicator-seletor/index.tsx
- client/src/containers/sidebar/survey-analysis-sidebar/user-sandbox-sidebar/index.tsx
- client/src/containers/sidebar/visualization-selector/index.tsx
- client/src/containers/widget/horizontal-bar-chart/index.tsx
- client/src/containers/widget/survey-analysis/index.tsx
- client/src/hooks/use-sandbox-widget.ts
- client/src/types.ts
- client/tests/widget/horizontal-bar-chart.test.tsx
- client/tests/widget/widget.test.tsx
- Introduced new `TransformedWidgetData` type to handle both raw and percentage-normalized data
- Updated widget components to use the new data structure
- Modified data transformation logic across multiple components
- Fixed horizontal bar chart to display raw values instead of percentages
- Fixed user sandbox widget not displaying correct value units
- Updated tests to reflect the new data structure
- [SIRH-219](https://vizzuality.atlassian.net/browse/SIRH-219)
[SIRH-219]: https://vizzuality.atlassian.net/browse/SIRH-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show absolute values in bar chart

- client/src/containers/explore/survey-analysis/index.tsx
- client/src/containers/widget/survey-analysis/index.tsx
- client/src/lib/normalize-widget-data.ts
- client/src/lib/utils.ts
- Extract `removeNaLabels` function to handle N/A entries in chart data
- Apply N/A label filtering to horizontal bar chart data
- Update number formatting locale from 'en-DE' to 'en-GB'
- Minor code organization improvements (import ordering)
> client: remove N/A labels for widgets data

- client/src/app/(root)/projections/layout.tsx
- client/src/containers/sidebar/filter-settings/clear-filters-button/index.tsx
- client/src/containers/sidebar/filter-settings/constants.ts
- client/src/containers/sidebar/filter-settings/index.tsx
- client/src/containers/sidebar/projections-sidebar/explore-sidebar/index.tsx
- client/src/containers/sidebar/survey-analysis-sidebar/explore-sidebar/index.tsx
- client/src/containers/sidebar/survey-analysis-sidebar/sandbox-sidebar/index.tsx
- client/src/containers/sidebar/survey-analysis-sidebar/user-sandbox-sidebar/index.tsx
- client/src/containers/widget/projections/index.tsx
- client/src/hooks/use-filters.ts
- client/src/lib/queryKeys.ts
- client/src/lib/utils.ts
- **New Filter System**: Added projections-specific filters with dedicated API integration
- **Enhanced Sidebar**: Integrated filter settings into the projections explore sidebar
- **Table View**: Added table visualization option for projections data
- **Filter Normalization**: Implemented country code to name mapping for better UX
- **Code Reorganization**: Extracted filter constants and improved component reusability
- [SIRH-200](https://vizzuality.atlassian.net/browse/SIRH-200)
[SIRH-200]: https://vizzuality.atlassian.net/browse/SIRH-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add basic and custom filters to projections explore page

- client/src/containers/scenarios/selector/index.tsx
- client/src/containers/widget/map/index.tsx
- client/src/hooks/use-scenario-filter.ts
This pull request introduces changes to the `ScenariosSelector` component and the `useScenarioFilter` hook to improve default behavior and streamline scenario selection logic. The most important changes include adding a `useLayoutEffect` to set a default scenario on mount and simplifying the `toggleScenario` function to only add scenarios if they are not already selected.
* [`client/src/containers/scenarios/selector/index.tsx`](diffhunk://#diff-b5d6e546c2d8e00dac0f2c26df77ef21b1930da6aec859be75dc4e752b7b7b40R11-R15): Added `useLayoutEffect` to automatically select the first scenario (`SCENARIOS[0].value`) when the `ScenariosSelector` component mounts. This ensures a default scenario is always selected.
* [`client/src/hooks/use-scenario-filter.ts`](diffhunk://#diff-fa49c30f6e14d31022a8b6e60 …
> [SIRH-229] fix(scenarios): At least one scenario must be selected. Set default scenario.

- api/src/infrastructure/postgres-projection-data.repository.ts
- shared/dto/projections/projection-visualizations.constants.ts
This pull request updates the handling of projection visualizations and improves filtering logic for custom widget data. The main changes include adding an explicit filter for chart widget types and refining the list of available visualizations to exclude tables.
**Visualization Filtering Enhancements:**
* For line, bar, and area charts, a new filter is added to `dataFilters` to ensure the widget data is filtered by the correct `type` using the vertical axis value and the `EQUALS` operator. This makes the data retrieval more precise.
* The import of `SEARCH_FILTERS_OPERATORS` from `@shared/dto/global/search-filters` is added to support the new filter logic.
**Visualization List Refinement:**
* The `AVAILABLE_PROJECTION_VISUALIZATIONS` list now excludes the `TABLE` visualization type, …
> Fix projections

- client/src/containers/sidebar/filter-settings/constants.ts
- client/src/hooks/use-filters.ts
- client/src/hooks/use-scenario-filter.ts
- client/src/lib/constants.ts
- client/src/lib/utils.ts
- shared/dto/projections/projection-filter.entity.ts
This pull request adds support for filtering projections by `unit` in the `PROJECTION_FILTER_NAME_TO_FIELD_NAME` mapping. This is a minor change that extends the available filters for projections.
> chore: Add unit to the projections filters
