.github/workflows/client-tests.yml, client/jest.config.ts, client/jest.setup.ts, client/package.json, client/pnpm-lock.yaml, client/tests/dummy-component.test.tsx, client/tests/dummy-component.tsx, client/tsconfig.json, package.json
This PR adds a basic scaffold to start implementing component testing using react-testing-library and jest
It also adds a CI workflow to run tests on gh actions
superseeds https://github.com/Vizzuality/4-growth/pull/2, please check this one before
=> (chore) Client test scaffold

.github/workflows/api-tests.yml, .github/workflows/client-tests.yml, .gitignore, README.md, api/Dockerfile, api/src/app.module.ts, api/src/main.ts, client/Dockerfile, docker-compose.yml, infrastructure/main.tf, infrastructure/modules/state/main.tf, infrastructure/modules/state/outputs.tf, infrastructure/modules/state/permissions.json, infrastructure/modules/state/variables.tf, infrastructure/providers.tf, infrastructure/variables.tf, infrastructure/vars/terraform.tfvars
Chore - First part of Infra 
This PR adds TF code to create a s3 bucket to store infra remote state, and adds Dockerisation for both client and api
Run standalone Docker containers (both client and api) or run by docker-compose files
=> (chore) infra scaffold + dockerisation - 1

.github/workflows/api-tests.yml, README.md, api/src/app.module.ts, api/src/modules/countries/countries.controller.ts, api/src/modules/countries/countries.module.ts, api/src/modules/countries/countries.service.ts, api/tsconfig.json, docker-compose.yml, pnpm-lock.yaml, shared/config/development.json, shared/contracts/country.contract.ts, shared/dto/countries/country.entity.ts, shared/dto/users/user.entity.ts, shared/package.json
In order to add database this PR:
- Adds postgres service to `docker-compose.yml`
- Connect nestJS with database
- Create `Country` entity 
- Add database service to workflow
[SIRH-17](https://vizzuality.atlassian.net/browse/SIRH-17)
[SIRH-17]: https://vizzuality.atlassian.net/browse/SIRH-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE](feat): add database [SIRH-17]

client/package.json, pnpm-lock.yaml
Remove non used @typescript-eslint/parser package on client
=> [FE](fix): remove eslint parser from client

client/src/app/page.tsx, client/src/containers/coming-soon/index.tsx
=> [FE](styles): fix mobile version

infrastructure/main.tf, infrastructure/modules/env/certificate.tf
Restores staging and prod envs TF code and requestes a new certificate for prod under a external domain
=> restore staging and prod tf config + prod certificate

package.json
=> pnpm@9.2.0

client/.env.test, client/next.config.js, client/package.json, client/src/env.js, pnpm-lock.yaml
=> adds environmental variables validation

client/next.config.js, client/src/app/providers.tsx
Updates base path of session endpoint.
=> [N/A] updates session base path

.github/workflows/api-tests.yml, .github/workflows/client-tests.yml, .github/workflows/e2e-tests.yml, api/src/decorators/get-user.decorator.ts, api/src/modules/users/users.controller.ts, api/test/auth/auth.spec.ts, api/test/auth/fixtures.ts, api/test/users/fixtures.ts, api/test/users/users.spec.ts, api/test/utils/test-manager.ts, api/test/utils/user.auth.ts, infrastructure/main.tf, pnpm-lock.yaml, shared/contracts/routes.ts, shared/contracts/user.contract.ts, shared/dto/users/user.dto.ts, shared/lib/entity-mocks.ts, shared/package.json
Adds a /users/me endpoint to get the user info based on the authenticated token
If the token is bound to an existing user, it returns its info
If the token content is not valid, its unauthorized
if the token can be decoded, but a user cannot be found by its content, its unauthorized
=> (feat) adds users/me endpoint

package.json
=> [N/A] pnpm@9.4.0

data/sql/base-seed.sql, shared/dto/custom-charts/custom-chart.entity.ts
Add column is_public and mock data to the repo
=> Data/sirh 62/mockup

e2e/playwright.config.ts
=> [N/A] sets NODE_ENV to API and client for running e2e tests

client/src/app/health/route.ts, client/src/middleware.ts
`/health` route will bypass the basic authentication and return a `200` when requested.
=> [N/A] adds health check endpoint

api/src/modules/custom-charts/custom-charts.controller.ts, api/test/custom-charts/custom-charts-crud.spec.ts, shared/contracts/custom-charts.contrac.ts, shared/dto/custom-charts/update-custom-chart.dto.ts, shared/dto/global/api-response.dto.ts
This PR introduces PATCH and DELETE handlers for custom charts
NOTE: Working on parallel to introduce zod schema validations at contract level, so for now we only allow to PATCH the name property, justo make the whole functionallity available. 
We will remove this next and use zod schemas, allowing to update all required properties
=> (feat) SIRH-64 custom charts patch and delete

infrastructure/source_bundle/.ebextensions/authorized_keys.config
=> [N/A] adds SSH public key

package.json
=> pnpm@9.5.0

client/src/containers/header/menu/index.tsx
fixes the routing to the contact form from the profile section
=> fix contact us routing

.github/workflows/deploy.yml
=> chore: Improve docker-compose.yml generation in deploy.yml

.github/workflows/deploy.yml
=> chore: Restore deploy workflow

.github/workflows/deploy.yml
=> chore(github): Update actions/upload-artifact version

api/package.json, client/package.json, e2e/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Unifies versions of `@types/node` and `typescript` through the catalog.
=> a @types/node to rule them all

client/package.json, pnpm-lock.yaml
bumps next to 14.2.10 to apply high severity security patch
=> bump nextjs security patch

client/src/app/(root)/explore/page.tsx, client/src/app/(root)/layout.tsx, client/src/app/providers.tsx, client/src/containers/explore/index.tsx, client/src/containers/explore/section/index.tsx, client/src/containers/explore/store.ts, client/src/containers/sidebar/index.tsx, client/src/lib/queryClient.ts, client/src/lib/queryKeys.ts, client/src/lib/utils.ts, e2e/tests/explore/explore.spec.ts, shared/lib/e2e-test-manager.ts
This PR finalize the subtasks from the [jira task](https://vizzuality.atlassian.net/browse/SIRH-114)
=> Sections implementation

shared/contracts/sections.contract.ts, shared/dto/widgets/base-widget-data.interface.ts, shared/dto/widgets/custom-widget.entity.ts, shared/dto/widgets/widget-visualizations.constants.ts
- Added filter and navigation to WIDGET_VISUALIZATIONS enum
- Added WidgetFilters and WidgetNavigationData to BaseWidgetWithData interface
- Fixed response type in sections contract
=> Extended widget visualisations and widget data types

client/next.config.js
Added Typeorm to ignoreWarnings in next config. More info on this issue can be found [here](https://github.com/typeorm/typeorm/issues/10047) and [here](https://github.com/typeorm/typeorm/issues/2158).
=> Ignore Typeorm warnings during build time

api/src/infrastructure/postgres-survey-data.repository.ts, client/src/containers/explore/section/overview-section/index.tsx, client/src/containers/widget/area-chart/index.tsx, client/src/containers/widget/filter/index.tsx, client/src/containers/widget/horizontal-bar-chart/index.tsx, client/src/containers/widget/index.tsx, client/src/containers/widget/navigation/index.tsx, client/src/containers/widget/pie-chart/index.tsx, client/src/containers/widget/single-value/index.tsx, client/src/lib/utils.ts, client/tests/widget/area-chart.test.tsx, client/tests/widget/horizontal-bar-chart.test.tsx, client/tests/widget/pie-chart.test.tsx, client/tests/widget/single-value.test.tsx, shared/dto/widgets/base-widget-data.interface.ts, shared/dto/widgets/widget.utils.ts
- Updated BaseWidgetWithData interface to support different data structures
- Updated PostgresSurveyDataRepository to compute the correct widget data response, please note that I didn't cover all use cases and added a TODO comment for this
- Updated frontend according to the new BaseWidgetWithData interface
=> Updated BaseWidgetWithData interface

.github/workflows/deploy.yml, api/package.json, api/src/app.controller.ts, api/src/app.module.ts, api/src/app.service.ts, api/test/e2e/health/health.spec.ts, client/src/app/health/route.ts, e2e/package.json, e2e/playwright.config.ts, infrastructure/source_bundle/proxy/conf.d/application.conf, pnpm-lock.yaml
This pull request introduces health check functionality to the API, updates dependencies, and includes various configuration changes. The most important changes include adding health check endpoints, updating the `pnpm-lock.yaml` file, and modifying deployment settings.
* [`api/src/app.controller.ts`](diffhunk://#diff-b158c72bea4fdd5db81bb63062d12fb84268c942348b6d5b2f7ed7b1e9968aa9R6-R32): Added health check endpoint using `@nestjs/terminus` to monitor database status.
* [`api/src/app.module.ts`](diffhunk://#diff-1f471e6c80bac8cc219f07df0fcbcb1729f2ec1f035268c30b034c8e687f258eR20-R26): Imported and configured `TerminusModule` for health checks.
* [`api/test/e2e/health/health.spec.ts`](diffhunk://#diff-d907d2ad846e293157617071b0bc2ac29bdf08264719e6612f68f3f0c17cb756R1-R46): Added …
=> Story/sirh 167 - BE - Create a liveness/health check in order to ensure the backend really up and working

client/src/containers/sandbox/index.tsx, client/src/containers/sidebar/breakdown-selector/index.tsx, client/src/containers/sidebar/filter-settings/index.tsx, client/src/containers/widget/breakdown/index.tsx, client/src/containers/widget/index.tsx, client/src/hooks/use-sandbox-widget.ts, client/src/lib/normalize-widget-data.ts, client/src/lib/queryKeys.ts, client/src/lib/utils.ts, client/tests/widget/breakdown.test.tsx, client/tests/widget/widget.test.tsx
- Implementation of the breakdown view
[Figma](https://www.figma.com/design/1MQAbB99h05eR5xbHqNDVn/4Growth-%5BInternal%5D?node-id=4246-88435&m=dev)
[SIRH-175](https://vizzuality.atlassian.net/browse/SIRH-175)
[SIRH-175]: https://vizzuality.atlassian.net/browse/SIRH-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FE - Add data breakdown view

api/data/sections/sections.json
- Only allow area_graph for `yes/no/don't know` questions
=> Updated sections.json

.github/workflows/deploy.yml
This pull request includes significant updates to the GitHub Actions workflow configuration in `.github/workflows/deploy.yml`. The primary changes involve adding a new job to detect changes in the client and API paths and updating the build jobs to conditionally run based on these detected changes.
Key changes include:
* Added a new `detect_changes` job to identify changes in client and API paths using the `dorny/paths-filter` action.
* Updated the `build_client` job to depend on both `set_environment` and `detect_changes` jobs and to conditionally run only if client changes are detected.
* Updated the `build_api` job to depend on both `set_environment` and `detect_changes` jobs and to conditionally run only if API changes are detected.
=> chore: Improve deployment github workflow

client/src/containers/filter/filter-select/filter-select-values/index.tsx
- Show apply button when form values are changed
=> Bugfix form state filter select

client/next.config.js, client/src/app/page.tsx
- Temporary redirect homepage to explore page
=> Temporary redirect homepage to explore page

api/src/infrastructure/postgres-survey-answers.repository.ts, api/test/e2e/widgets/base-widgets.spec.ts, client/src/containers/widget/index.tsx, client/src/containers/widget/map/index.tsx, client/src/containers/widget/map/map.utils.ts, client/src/types.ts, client/tests/widget/map.utils.test.ts
- Shows scale colors in map widget according to data from API
=> Real implementation map widget

client/src/containers/widget/create-widget/index.tsx, client/src/containers/widget/update-widget/index.tsx
[Jira](https://vizzuality.atlassian.net/browse/SIRH-153)
=> Bugfix save custom widget

client/src/containers/sidebar/explore-sidebar/index.tsx, client/src/containers/sidebar/filter-settings/clear-filters-button/index.tsx, client/src/containers/sidebar/filter-settings/filter-popup/index.tsx, client/src/containers/sidebar/sandbox-sidebar/index.tsx, client/src/containers/sidebar/user-sandbox-sidebar/index.tsx
[SIRH-190](https://vizzuality.atlassian.net/browse/SIRH-190)
[SIRH-190]: https://vizzuality.atlassian.net/browse/SIRH-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FE - Filters enhancement

client/src/containers/header/index.tsx, client/src/containers/header/menu/index.tsx, client/src/containers/widget/index.tsx, client/src/containers/widget/widget-header/index.tsx, client/src/lib/normalize-widget-data.ts
- Filter the N/A answers in the breakdown chart
- Hide the response rate in the breakdown chart (Until API response is able to return the data needed to compute this)
=> Bugfixes breakdown chart

client/src/containers/about/index.tsx
[SIRH-196](https://vizzuality.atlassian.net/browse/SIRH-196)
[SIRH-196]: https://vizzuality.atlassian.net/browse/SIRH-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update text in the "about" page

client/src/containers/widget/pie-chart/index.tsx, client/src/lib/constants.ts, client/src/lib/normalize-widget-data.ts, client/src/lib/utils.ts, client/tests/widget/pie-chart.test.tsx
- Added data normalization to handle large datasets by grouping smaller segments into "Others" category
- Improved number formatting for percentage values
- Added responsive legend layout with better spacing and wrapping
- Added test coverage for new functionality
- [SIRH-213](https://vizzuality.atlassian.net/browse/SIRH-213)
[SIRH-213]: https://vizzuality.atlassian.net/browse/SIRH-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Pie Chart Improvements

api/package.json, api/src/modules/widgets/page-filters.service.ts, api/test/e2e/page-filters/page-filters-crud.spec.ts, pnpm-lock.yaml
This pull request introduces enhancements to the `PageFilters` feature by adding support for query-based filtering and improving the underlying service logic. The most important changes include modifying the `PageFiltersController` to accept query parameters, extending the `PageFiltersService` to process filters dynamically, and updating the contract to define the query schema.
* Modified the `searchPageFilters` method in `PageFiltersController` to accept query parameters and pass them to the service for dynamic filtering. (`api/src/modules/widgets/page-filters.controller.ts`, [api/src/modules/widgets/page-filters.controller.tsL15-R16](diffhunk://#diff-fc9791469aad831813bdb3548ea0508064f3a193ad3f9f13b863147152c98fe9L15-R16))
* Updated `PageFiltersService` to include logic for applying …
=> feat: Create smart filters for Survey answers

client/package.json, client/src/containers/widget/horizontal-bar-chart/index.tsx, client/src/containers/widget/utils.ts, client/src/containers/widget/vertical-bar-chart/index.tsx, client/src/types/recharts.d.ts, client/tests/widget/vertical-bar-chart.test.tsx, pnpm-lock.yaml
- Upgraded Recharts from v2.12.7 to v2.15.3
- Added new `VerticalBarChart` component
- Added unit tests suite for `VerticalBarChart` component
- [SIRH-203](https://vizzuality.atlassian.net/browse/SIRH-203)
[SIRH-203]: https://vizzuality.atlassian.net/browse/SIRH-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add VerticalBarChart component

client/src/containers/widget/area-chart/index.tsx, client/src/containers/widget/area-graph/index.tsx, client/src/containers/widget/projections/index.tsx, client/src/containers/widget/survey-analysis/index.tsx, client/tests/widget/area-graph.test.tsx, client/tests/widget/widget.test.tsx
- Split the original `AreaChart` component into two specialized components:
- `AreaChart`: New component for displaying projection data using Recharts
- `AreaGraph`: Renamed from original `AreaChart` for survey analysis visualization
- Improved test coverage and error handling
- [SIRH-205](https://vizzuality.atlassian.net/browse/SIRH-205)
[SIRH-205]: https://vizzuality.atlassian.net/browse/SIRH-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Projections AreaChart widget

api/src/infrastructure/data-source-manager.ts, api/src/infrastructure/fs/fs.utils.ts, api/src/migrations/1759309688707-migrations.ts, api/test/e2e/page-filters/page-filters-crud.spec.ts, api/test/e2e/projections/custom-projection.spec.ts, api/test/e2e/projections/projections.spec.ts, api/test/integration/app.spec.ts, api/test/integration/page-filter.repository.spec.ts, client/src/containers/sidebar/breakdown-selector/index.tsx, client/src/containers/sidebar/indicator-seletor/index.tsx, client/src/containers/sidebar/projections-sidebar/sandbox-settings/bubble-select/index.tsx, client/src/containers/sidebar/projections-sidebar/sandbox-settings/color-select/index.tsx, client/src/containers/sidebar/projections-sidebar/sandbox-settings/horizontal-select/index.tsx, client/src/containers/sidebar/projections-sidebar/sandbox-settings/size-select/index.tsx, client/src/containers/sidebar/projections-sidebar/sandbox-settings/vertical-select/index.tsx, client/src/hooks/use-settings.ts, shared/dto/global/configuration-params.ts, shared/dto/projections/custom-projection-settings.ts, shared/lib/db-entities.ts, shared/lib/db-helpers.ts, shared/schemas/custom-projection-settings.schema.ts
This pull request includes minor improvements to both the backend and frontend codebases, focusing on error handling and type safety.
Frontend improvements:
* Ensured that the `widgets` variable in `BreakdownSelector` is always an array, preventing potential errors if `data` is `null` or `undefined`. (`client/src/containers/sidebar/breakdown-selector/index.tsx`, [client/src/containers/sidebar/breakdown-selector/index.tsxL30-R30](diffhunk://#diff-5104c25b1855a1118184b7e3ce81d8202193d3fa3d8c4ae3ee61528b2c03565fL30-R30))
Backend improvements:
* Added a `label` property to the test data in the `PageFilterRepository` integration test, which helps clarify the test case and may prevent issues related to missing required fields. (`api/test/integration/page-filter.repository.spec.ts`, …
=> Pre production fixes
